"""Curate Tier-1 raw datasets -> Tier-2 committed artifacts.

The two-tier data model (docs/adr, hosting design 2026-07-24):

  TIER 1  raw, git-ignored, ~786 MB   data/sisfall/**  data/casas/**
             |  this script, run ONCE by a dev
             v
  TIER 2  curated, git-tracked, ~hundreds of KB   data/curated/*.json
             |
             v
  RUNTIME (fresh clone / Render): reads Tier 2 only. Zero download, REAL data.

Runtime never touches the 786 MB again: it only needs a handful of real fall
traces (the Simulate rotation + drilldown waveform) and a small feature table
(the judge-metrics logistic regression). Both are produced here, from the SAME
loaders + detector the service uses, so nothing about the signal is faked or
lossily resampled — fall windows are stored at full 200 Hz.

Run (real interpreter, needs numpy):
    cd scoring-service
    C:\\Users\\lucas\\anaconda3\\python.exe scripts/curate.py

Outputs (committed):
    data/curated/falls.json      distinct real falls for the rotation
    data/curated/features.json   [peak_g, freefall_depth, impact_energy, stillness] x label
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# make `app` importable when run as `python scripts/curate.py` from scoring-service/
_SERVICE_ROOT = Path(__file__).resolve().parents[1]
if str(_SERVICE_ROOT) not in sys.path:
    sys.path.insert(0, str(_SERVICE_ROOT))

import numpy as np  # noqa: E402

from app.data import loaders  # noqa: E402
from app.scoring import acute  # noqa: E402

CURATED_DIR = loaders.DATA_DIR / "curated"
FS = loaders.SISFALL_FS

# how many distinct real falls to bake into the rotation, and how big the
# LR feature sample per class is. Kept small so the committed JSON stays tiny.
N_ROTATION = 6
N_PER_CLASS = 250
# seconds of context kept around each fall so detection + drilldown + the
# stillness feature are all faithful, without committing a 15 s recording.
PRE_S = 1.0
POST_S = 8.0


def _window(smv: np.ndarray, res: acute.FallResult) -> np.ndarray:
    """Trim the full trace to [dip_start - PRE_S, impact + POST_S] so the
    committed array is small but the ordered fall signature + stillness survive.
    Falls back to the whole trace if the phases weren't located."""
    if res.dip_start_idx < 0 or res.impact_idx < 0:
        return smv
    start = max(0, res.dip_start_idx - int(PRE_S * FS))
    end = min(smv.size, res.impact_idx + int(POST_S * FS))
    return smv[start:end]


def build_falls() -> dict:
    """Distinct real SisFall falls -> self-contained curated rotation.

    Reuses loaders.demo_rotation_traces (one detected fall per subject, peak-g
    spaced) so the curated set matches what the live rotation already picks."""
    paths = loaders.demo_rotation_traces(n=N_ROTATION)
    if not paths:
        raise SystemExit(
            "no SisFall data on disk (data/sisfall/); fetch Tier-1 first "
            "(datasets.lock.json -> source_url) before curating."
        )
    traces = []
    for p in paths:
        smv = loaders.sisfall_smv(p)
        res = acute.detect_fall(smv, FS)
        win = _window(smv, res)
        traces.append({
            "id": p.stem,
            "subject": p.parent.name,
            "file": p.name,
            "fs": FS,
            "peakG": round(res.peak_g, 3),
            "freefallMs": round(res.freefall_ms, 1),
            "confidence": round(acute.acute_confidence(res), 3),
            "samples": [round(float(v), 4) for v in win],
        })
    return {
        "$comment": "GENERATED by scripts/curate.py from Tier-1 SisFall. "
                    "Committed so runtime needs no raw dataset. Full 200 Hz "
                    "windows — the live detector runs on these unchanged.",
        "source": "SisFall (Sucerquia et al., 2017)",
        "fs": FS,
        "traces": traces,
    }


def _features_for(smv: np.ndarray) -> list[float]:
    """4 physical features the judge-page classifier learns on."""
    res = acute.detect_fall(smv, FS)
    peak_g = float(res.peak_g)                       # impact magnitude
    freefall_depth = float(np.min(smv))              # lowest dip (free fall -> ~0)
    impact_energy = float(peak_g - freefall_depth)   # dynamic range across the event
    stillness = float(res.post_impact_still_s)       # rest after impact (falls: high)
    return [round(peak_g, 4), round(freefall_depth, 4),
            round(impact_energy, 4), round(stillness, 4)]


def _sample(glob: str, label: int, cap: int) -> tuple[list, list]:
    """Deterministic sample of up to `cap` files matching `glob`, one class."""
    files = sorted(loaders.SISFALL_DIR.rglob(glob))
    if len(files) > cap:  # even stride keeps subject diversity, no RNG needed
        step = len(files) / cap
        files = [files[int(i * step)] for i in range(cap)]
    rows, labels = [], []
    for f in files:
        try:
            rows.append(_features_for(loaders.sisfall_smv(f)))
            labels.append(label)
        except (ValueError, OSError):
            continue
    return rows, labels


def build_features() -> dict:
    """Balanced [features, label] table over real falls (F*) and ADLs (D*)."""
    fx, fy = _sample("F*.txt", 1, N_PER_CLASS)
    dx, dy = _sample("D*.txt", 0, N_PER_CLASS)
    return {
        "$comment": "GENERATED by scripts/curate.py from Tier-1 SisFall. Feature "
                    "table for the judge-metrics classifier (app/model/training.py).",
        "featureNames": ["peakG", "freefallDepth", "impactEnergy", "stillnessS"],
        "X": fx + dx,
        "y": fy + dy,
        "counts": {"falls": len(fy), "adls": len(dy)},
    }


def main() -> None:
    CURATED_DIR.mkdir(parents=True, exist_ok=True)
    for name, payload in (("falls.json", build_falls),
                          ("features.json", build_features)):
        data = payload()
        out = CURATED_DIR / name
        out.write_text(json.dumps(data, ensure_ascii=False) + "\n", encoding="utf-8")
        kb = out.stat().st_size / 1024
        print(f"wrote {out.relative_to(_SERVICE_ROOT)}  ({kb:.1f} KB)")


if __name__ == "__main__":
    main()
